version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python app/manage.py runserver 0.0.0.0:8000
    env_file: .env
    image: app:latest
    volumes:
      - .:/code
    environment:
      - DB_HOST=db
      - DB_NAME=mydb-dev
      - DB_USER=user
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=mydb-dev
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
